### ISSUE TITLE
Optimize import

### ISSUE THREAD

**Issue by aristippe** [aristippe/pathagar#11]
Currently, the entire ePub is unzipped when importing to retrieve metadata. Batch importing, particularly when it includes large ePubs, could see a great gain in speed, perhaps helpful when successively testing large numbers of imports, if we unzip only the needed files. They would be:
1. META-INF/container.xml - contains location of OPF
2. .opf - also contains location of cover
3. cover - unzip only if an image file

**Comment by sinergatis** [comment]
Closed on #17!
