### ISSUE TITLE
HTML in ePub descriptions

### ISSUE THREAD

**Issue by aristippe** [aristippe/pathagar#12]
HTML is often specified in descriptions using HTML entities, such as italics being &lt;i&gt;. Perhaps replacing less than and greater than would be enough to get the descriptions to display properly.

https://wiki.python.org/moin/EscapingHtml

**Comment by sinergatis** [comment]
Yeah, good catch - noticed it even on my very-small-test-epubs suite! The fix on https://github.com/aristippe/pathagar/commit/2890f94a73de4138e725584dd0a8da21d6749bb3 makes much sense (and probably a handful of other fields in that and other templates should be escaped too, just in case).

**Comment by aristippe** [comment]
Cool. First issue closed! :)

edit: And indeed there could be a few other fields. I've only noticed it in descriptions so far though there could be others.

**Comment by aristippe** [comment]
Close with 2890f94a73de4138e725584dd0a8da21d6749bb3.
