### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by aristippe** [aristippe/pathagar#24]
Since it was something I was hoping for in the next few months, and it didn't seem so bad, why not. I've started and it looks ok so far. No problems with trans and blocktrans template tags or localized model fields. The template will include other changes and fixes as I look thru it to localize. Once it's fairly complete, I'll push up a branch for review.

**Comment by sinergatis** [comment]
Sounds good! I'd advise trying to go through the internationalization docs first, in order to assess the changes  introduced by more recent Django versions - basically for making sure they are not that many, and if so, probably keep them in mind.

**Comment by aristippe** [comment]
A good idea to look through the updated internationalization docs.

I haven't done a thorough review of strings in the python files that could be localized. Most of what is forward facing to the user, except for perhaps a few parts of the site I haven't used much so far, is setup for localization, even if not all the translations are there for the one so far. If you did have a chance to look at it, that'd be great. As you likely know, 'django-admin.py compilemessages', setting LANGUAGE_CODE (local_settings seems to be the best place) to 'fr', and restarting the server should be enough. Except for localized model and table names in admin which I'm not too concerned about and it an certainly wait, even til eternity, I was curious about why some strings don't translate. For instance, 'Log Out' in the header or the download button in book_detail. Very strange but maybe I'm missing something.

**Comment by sinergatis** [comment]
I think that by default Django provides some strings (like the ones used on the admin, etc) that might override your translation - you can quickly testing by changing `LANGUAGE_CODE` to a locale supported by Django, and see that some strings are in that language in the main app.

And don't worry about it not being 100% complete, we can refine it later, as usual! If you are satisfied with the work in your branch so far, feel free to issue a pull request (and let me know if you prefer me to take care of the merging conflicts, as the latest pulls left the branch with some conflicts I think),

**Comment by aristippe** [comment]
Some of the untranslated strings seemed weird since they're trans tags within templates. They look all the same to me and why a handful don't translate (besides the ones I haven't gotten to yet) is a mystery to me!

Me too I think we can always refine it later and it seems pretty good for now. A merge would be great since it does modify a fair amount of files, even if the change might simply be enclosing strings with ugettext*. It'll certainly be simpler for any other changes we'd like to make.

No worries about the merging. You've certainly done quite a bit this week! I was going to take a look at that soon, since I noticed tagging didn't seem to work in 'localize' though it might have been a quirk. Hopefully I'll be able to take care of the conflicts; at least I'll try my best. Likely sometime later today I'll push up another commit so you can take a look tomorrow or whenever.
