### ISSUE TITLE
Revise taggit vs tagging situation

### ISSUE THREAD

**Issue by sinergatis** [aristippe/pathagar#25]
Related to #4, cleaning up and clarifying the status of the tag library used would be a good idea, as `django-tagging` is no longer developed and, while it seems that upstream introduced `django-taggit` as a replacement, there are pieces of `django-tagging` still lying around on the codebase.

Ideally, it _seems_ that we should remove `django-tagging` completely while making sure things don't break and the tag feature (regardless of the app used for it) works as originally intended.

**Comment by aristippe** [comment]
Sounds good. I haven't tried tagging though was very curious about it!

**Comment by sinergatis** [comment]
I haven't tested it extensively neither, but it seems that adding a tag manually on the admin makes it available on the "tags" view as expected, and can be assigned to books, etc; although when using the add book or edit book view it the tags are ignored or not handled at all. It _seems_ that the groundwork is there, we just need to glue the pieces back together and remove the old references.

**Comment by sinergatis** [comment]
With the Django upgrade came the official removal of `django-tagging`. In a very lazy way, `views.tags()` has been temporarily modified so it always returns _all_ the tags, as I didn't have the time to dig into `django-taggit`. This should be fixed at some point!

**Comment by sinergatis** [comment]
04dc1f556d738682abe9f9691eb7a36e2193eed4 should allow the tags to be used again, saving them when adding a book via the UI and when editing it as well.

There are however a couple of open issues:
- There is a `TagGroup` model, along with a couple of views, which seem to handle "tag groups", which have been left untouched as they _seem_ to be not really reachable by the user and left-overs of old versions. We need to further investigate how they intended to be used and go through the main repo, the specs, atom feeds, etc. to find if they are really a feature to take into account.
- Empty tags are not deleted when unused (ie. a book is edited to remove a tag, and that tag is left on the DB but unused). I have chosen to consider that a "feature" rather than a bug (for example, admins might have a list of tags they decide are standard, so they want them to be present even if empty). We might want to show only the used tags for presentational purposes (ie. the view tags page), though.

**Comment by aristippe** [comment]
Awesome! I also am not sure what TagGroup does though I have not taken a look much at the tagging code. I agree empty tags are best left in. Eventually, adding books per tag in the tag view, as well as similar new views for author and publisher, would help for management. Not a big thing but maybe someday.

I'll try adding some tags as well as updating the templates a bit for how they're displayed.

**Comment by sinergatis** [comment]
Finally closed at fded16bca8711778cf458ab855ad20bdaa12a0fd by deleting `TagGroup` and its related views/urls/etc. The consensus seems to be that `TagGroup` was not serving any real purpose, and probably was used on the past for providing tag "categories" of sorts (maybe as an aid to faceted searches on the feed).
