### ISSUE TITLE
Upgrade to latest Django

### ISSUE THREAD

**Issue by aristippe** [aristippe/pathagar#4]
1.4's support ended on October 1st, 2015 and is no longer receiving bug fixes and security updates. The oldest still supported version is 1.8, currently supported until at least April 2018. Upgrades per version, 1.4->1.5, 1.5->1.6, etc. seems like the best method, dealing with deprecations as they come with each version. The first one I found with 1.5 is django.views.generic.list_detail.object_detail, replaced with a class-based generic view.

https://docs.djangoproject.com/en/1.4/topics/generic-views-migration/

**Comment by sinergatis** [comment]
+1! Perhaps not top-priority at the moment, but definitely should upgrade at some point.

And actually it might not be a ~~good~~ bad idea to just upgrade directly to 1.8 or 1.9 whenever the time comes. Usually dealing with the deprecation and changes is quite systematic, and it _should_ be a relatively straight-forward and not so daunting task (this said, I did not look into the changes that would be needed yet).

**Comment by aristippe** [comment]
Yeah, I tried and there were quite enough changes. Upgrading per version whenever it's convenient looks like the better path. Indeed it can wait until we can get around to it. I don't see any new views needed at the moment, though if that happens, maybe it'd be convenient to update some other views to class-based together.

**Comment by sinergatis** [comment]
Made some progress on this issue: currently, on a [temporary branch on my repo](https://github.com/sinergatis/pathagar/tree/django-upgrade), I have a (hopefully) successfully upgrade up to 1.6.11 (e72976c92e7165f4335b35cbaedd693b65a849e6). The changes involved are described on the commit messages.

However, it seems that for gracefully upgrading to 1.7.11+, the reorganizing proposed on #13 (at least a very basic reorganizing) is needed - 11a68874b87b6b4a89cde35b1127998cc3c23004 required to update `manage.py` anyway, and the `sys.path` hack introduced by that commit is causing quite some trouble on 1.7+, preventing the tests to be run, and other issues _most likely_ related to the PYTHON_PATH and the structure.

I'm wondering if it would be a good idea to place a higher priority on fixing #13 (at least, make the minimum amount of changes so Django can be upgraded further?)? It is basically a matter of moving files around, and hopefully github is smart enough to show the previous changes properly, so my biggest concern is how much this would impact other features we are working at the moment (to my knowledge, "only" #24 and  #23?)

**Comment by aristippe** [comment]
Most excellent you were able to make such progress so quickly! I agree fixing #13 looks like a good idea. I pushed my localize branch, so feel free to review, merge, and continue with the upgrades. I'll hold off on anything future changes, until the upgrades get sorted out. Very nice!

**Comment by sinergatis** [comment]
The upgrade to Django 1.9.2 should be in master now, although there are quite a few issues to take care during a "cleanup round":

Included in #30:
- [x] Update `README.mkd` Quickstart (4689d1d5a52450dc7922905c4d2b8a623b54656f)
- [x] Revise uploaded file names 212b368
- [x] Update rest of dependencies to recent versions 02ccb6b
- [x] Complete taggit functionality (`tags()` view) #25 04dc1f556d738682abe9f9691eb7a36e2193eed4
- [x] Deprecated `render_to_string` usage (`books/selectwithpop`) a883fa09290e73699c449b89bb92ba54e21942e5
- [x] Update commands to use `argparse` bbb7bd5

.
- [ ] Decide on the initial fixtures (`Status`es - include as migration?)
- [x] Look into `books/add_settings.py` (it's probably obsolete)
- [x] Look into `popuphandler` + templates (probably unused, related to #3)
- [x] Revise book editing forms and validation
- [ ] Fix fabric and setuptools deployment

Some of those probably merit an issue, others are quite tiny fixes. Feel free to comment on other issues that will probably be found during testing!

**Comment by sinergatis** [comment]
Marked some stuff as completed on the previous checklist.

We should keep an eye on userena, as there is an issue and a pull request for Django 1.9 compatibility - as soon as a new version is out, we probably want to update as currently some nasty deprecation warnings are being thrown around due to stepping back to 1.8.

**Comment by aristippe** [comment]
Cool! Looking at the userena pull request comments, this week (or soon) for a new version is possible.

**Comment by sinergatis** [comment]
The userena new version has finally been released, so closing it after #52 !
