### ISSUE TITLE
Fix feeds so they take into account Author changes

### ISSUE THREAD

**Issue by sinergatis** [aristippe/pathagar#40]
Currently it seems that the feeds are broken and crash, most likely due to the model changes related to `Author`. I'm wondering if you could take a look at them and fix it, as it hopefully it is mainly a matter of applying very similar changes to those applied to the main book list view?

Even if we have not really placed too much emphasis on the OPDS part yet, I believe that at the very minimum we should try to have them working again, as ... well ... Pathagar is meant to be an OPDS server, after all!

**Comment by sinergatis** [comment]
b53a221d2a9cf4b98bf5301445bc42fe74d80180 attemps to fix the feeds by making sure `authors` and `publishers` are passed as a proper list of values, which seems to be working for the simpler cases. Further work is needed to make sure they do work as intended in more complex cases.

**Comment by sinergatis** [comment]
Marking it as closed!

**Comment by aristippe** [comment]
Thank you so much for taking care of it!
